### PR TITLE
rustfmt

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2887212 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2887212 with merge 2887212...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cast.rs/builds/199828107)
Approved by: japaric
Pushing 2887212297304e9980caa67bdddc0c143b657c69 to master...

**Pull request merged**
