### PR TITLE
use trust and drop the unstable feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8c47e29 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8c47e29 with merge 8c47e29...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cast.rs/builds/199822839)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 283bf05 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 283bf05 with merge 283bf05...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cast.rs/builds/199823504)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4079c87 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4079c87 with merge 4079c87...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit abd847b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit abd847b with merge abd847b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cast.rs/builds/199826050)
Approved by: japaric
Pushing abd847b2c687509d15fe4c9ddfbb8540a5602bb8 to master...

**Pull request merged**
